from enum import Enum, unique
import os

MS_PER_SECOND = 1000

FTX_BASE_REST_API = "https://ftx.us/api/"
FTX_ORDER_ENDPOINT = "orders"
FTX_US_API_KEY = os.environ["FTX_US_API_KEY"]
FTX_US_API_SECRET = os.environ["FTX_US_API_SECRET"]
FTX_US_KEY_HEADER = "FTXUS-KEY"
FTX_US_SIGNATURE_HEADER = "FTXUS-SIGN"
FTX_US_TIMESTAMP_HEADER = "FTXUS-TS"

KRAKEN_BASE_REST_API = "https://api.kraken.com"
KRAKEN_API_VERSION = "0"
KRAKEN_ORDER_ENDPOINT = "AddOrder"
KRAKEN_CANCEL_ALL_ORDERS_ENDPOINT = "CancelAll"
KRAKEN_OPEN_ORDERS_ENDPOINT = "OpenOrders"
PATH_TO_KRAKEN_KEYS = os.environ["KRAKEN_KEYS_PATH"]
KRAKEN_KEY_HEADER = "API-KEY"
KRAKEN_SIGNATURE_HEADER = "API-SIGN"
KRAKEN_API_KEY = os.environ["KRAKEN_API_KEY"]
KRAKEN_API_SECRET = os.environ["KRAKEN_API_SECRET"]


@unique
class HttpMethod(Enum):
    POST = "POST"
    GET = "GET"
    DELETE = "DELETE"
    PUT = "PUT"
    PATCH = "PATCH"
